---
# Prefer using Env Vars to set AWS Access & Secret Keys named as such:
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY 
aws_access_key: 
aws_secret_key: 
aws_region: us-east-1

student_count: 1
student_prefix: cisco-student

vpc_id: vpc-09153a8a908e9fd82
internet_gateway_id: igw-018de0b211b46db49
subnet_range_primary: 10.1.0.0/16
subnet_range_secondary: 198.18.0.0/16

s3_bucket: 'cisco-hol-cft-template'

asav_ami: ami-01b0bfec54ba93d12
ldap_ami: ami-028825c353dcebbf5
mssql_ami: ami-026647c105e33d1e2
iis_ami: ami-056344c5ab8499f66
mysql_ami: ami-08da13b95d975309c
apache_ami: ami-0632afd28934333ab
ansible_ami: ami-0cf82484c962af005
tet_data_ami: ami-0b9baab4aee1932c0
tet_edge_ami: ami-0aea03f5f48950bcd
employee_ami: ami-098c9dfaa8e66a018
sysadmin_ami: ami-042dbd8a78d99e538
attack_server_ami: ami-0c87027d46eea9a78
guacamole_ami: ami-023987711fc51f2d6
eks_worker_ami: ami-00c0ebc8b70d7e97c
